Teste/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

Tutorial/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Teste.urls')),
    path('hamburguer/', include('hamburguer.urls')),
    path('admin/', admin.site.urls),
]

hamburguer/urls.py
from django.urls import path

from . import views

app_name = 'hamburguer'
urlpatterns = [
    path('', views.HamburguerListView.as_view(), name='index'),
    path('search/', views.search_hamburguer, name='search'),
    path('create/', views.HamburguerCreateView.as_view(), name='create'),
    path('<int:pk>/', views.HamburguerDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.HamburguerUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.HamburguerDeleteView.as_view(), name='delete'), 
    path('<int:hamburguer_id>/comment/', views.create_comment, name='create_comment'),
    path('lists/', views.CategoryListView.as_view(), name='lists'),
    path('lists/create/', views.CategoryCreateView.as_view(), name='create-list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

Teste/models.py
from django.db import models

# Create your models here.

hamburguer/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now_add=True)
    opnion = models.TextField(max_length=2047)
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now_add=True)
    hamburguer = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

Comment.objects.order_by("data")

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    hamburgueria = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

hamburguer/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Comment

class HamburguerForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'location',
            'opnion',
            'poster_url',
        ]
        labels = {
            'name': 'Hamburgueria',
            'location': 'Localização',
            'opnion' : 'O que você achou desse lugar?',
            'poster_url' : 'URL da Foto',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

Teste/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'Teste/index.html', context)

def about(request):
    context = {}
    return render(request, 'Teste/about.html', context)

hamburguer/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Post, Comment, Category
from .forms import HamburguerForm, CommentForm
from django.shortcuts import render, get_object_or_404
from django.views import generic

class HamburguerDetailView(generic.DetailView):
    model = Post
    template_name = 'hamburguer/detail.html'
    context_object_name = 'hamburguer'


class HamburguerListView(generic.ListView):
    model = Post
    template_name = 'hamburguer/index.html'
    context_object_name = 'hamburguer_list'
   
def search_hamburguer(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        hamburguer_list = Post.objects.filter(name__icontains=search_term)
        context = {"hamburguer_list": hamburguer_list}
    return render(request, 'hamburguer/search.html', context)

class HamburguerCreateView(generic.CreateView):
    model = Post
    template_name = 'hamburguer/create.html'
    form_class = HamburguerForm
    
    def get_success_url(self):
        return (reverse('hamburguer:detail', args=(self.object.id, )))


class HamburguerUpdateView(generic.UpdateView):
    model = Post
    template_name = 'hamburguer/update.html'
    context_object_name = 'hamburguer'
    fields = ['name', 'location', 'opnion', 'poster_url']

    def get_success_url(self):
        return reverse('hamburguer:detail', args=(self.object.id, ))


class HamburguerDeleteView(generic.DeleteView):
    model = Post
    template_name = 'hamburguer/delete.html'
    context_object_name = 'hamburguer'
    success_url = reverse_lazy('hamburguer:index')

def create_comment(request, hamburguer_id):
    hamburguer = get_object_or_404(Post, pk=hamburguer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            hamburguer=hamburguer)
            comment.save()
            return HttpResponseRedirect(
                reverse('hamburguer:detail', args=(hamburguer_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'hamburguer': hamburguer}
    return render(request, 'hamburguer/create_comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'hamburguer/lists.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'hamburguer/create_list.html'
    fields = ['name', 'author', 'hamburgueria']
    success_url = reverse_lazy('hamburguer:lists')

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'hamburguer/category_detail.html'
    context_object_name = 'category'

Teste/templates/Teste/about.html
{% extends 'base.html' %}

{% block content %}
<h1>Sobre esse Site</h1>
Esta página foi criada pelo aluno Thales Travaglini Galanti, nº USP 11258116, para contemplar a segunda atividade do laboratório da disciplina "PMR3304 - Sistemas de Informação".
{% endblock content %}

Teste/templates/Teste/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Sampaguerias</i></h1>
<p>A Página para Comunidade apreciadora de Hamburguers</p>
{% endblock content %}

Teste/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'LOGO.jpg' %}"> </a> 
        <h1>Sampaguerias</h1>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'hamburguer:index' %}">Hamburguerias</a></li>
                <li><a href="{% url 'hamburguer:lists' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header> 
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright Thales Stark 2021</small>
        </p>
    </footer>
</body>

</html>

hamburguer/templates/hamburguer/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }} 
{% endblock title %}

{% block content %}
<h2>Detalhes da Hamburgueria {{ category.name }} </h2>

<hr>

<section class="dados-de-hamburgueria">
    <ul>
        <li>Nome: {{ category.name }}</li>
        <li>Autor: {{ category.author }}</li>
        {% for post in category.hamburgueria.all %}
        <article class="card">
            <a href="{% url 'hamburguer:detail' post.id %}"><img src="{{ post.poster_url }}" height='300'
                alt="Poster da Hamburgueria {{ post.name}}"></a>
            <p>{{ post.name }} </p>
        </article>
        {% endfor %}   
    </ul>
</section>

{% endblock content %}

hamburguer/templates/hamburguer/create.html
{% extends 'base.html' %}

{% block title %}
Adicionar Hamburgueria
{% endblock title %}

{% block content %}
<h2>Adicionar Hamburgueria</h2>

<form action="{% url 'hamburguer:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

hamburguer/templates/hamburguer/create_comment.html
{% extends 'base.html' %}

{% block title %}
Adicionar Comentário
{% endblock title %}

{% block content %}
<h2>Adicionar Comentário</h2>

<form action="{% url 'hamburguer:create_comment' hamburguer.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comentar</button>
</form>

{% endblock content %}

hamburguer/templates/hamburguer/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar lista de Hamburguerias
{% endblock title %}

{% block content %}
<h2>Criar Lista</h2>

<form action="{% url 'hamburguer:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

hamburguer/templates/hamburguer/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'hamburguer:delete' hamburguer.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a Hamburgueria "{{ hamburguer.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

hamburguer/templates/hamburguer/detail.html
{% extends 'base.html' %}

{% block title %}
{{ hamburguer.name }} 
{% endblock title %}

{% block content %}
<h2>Detalhes da Hamburgueria {{ hamburguer.name }} </h2>

<hr>

<section class="dados-de-hamburgueria">
    <ul>
        <li>Nome: {{ hamburguer.name }}</li>
        <li>Data de Postagem: {{ hamburguer.data|date:"d/m/Y"}} </li>
        <img src="{{hamburguer.poster_url}}" alt="Imagem da Hamburgueria" height="300">
        <li>Lugar: {{ hamburguer.location }}</li>
        <li>Opnião: {{ hamburguer.opnion|safe }}</li>
        {% if hamburguer.list_set.all %}
           <li>Incluso nas listas: {{ hamburguer.list_set.all|join:", " }} </li>
        {% endif %}
       
        <li><a href="{% url 'hamburguer:update' hamburguer.id %}">Editar</a></li>
        <li><a href="{% url 'hamburguer:delete' hamburguer.id %}">Apagar</a></li>
    </ul>
</section>

<hr>
<h2>Comentários</h2>
<a href="{% url 'hamburguer:create_comment' hamburguer.id %}">Comentar</a>
<section class = "Comentarios">
    {%if hamburguer.comment_set.all%}
    {% for comment in hamburguer.comment_set.all %}
    <h4>{{comment.author}}</h4>
    <p>{{comment.text}}</p>
    <p>{{comment.data|date:"d/m/Y"}}</p>
    {% endfor %}
    {%else%}
    <p>Não exitem comentários</p>
    {%endif%}
</section>

{% endblock content %}

hamburguer/templates/hamburguer/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos as Hamburguerias</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'hamburguer:search' %}">Buscar Hamburgueria</a></p>
    <p>Não encontrou a Hamburgueria? <a href="{% url 'hamburguer:create' %}">Adicionar Nova Hamburgueria</a></p>
</section>
{% if hamburguer_list %}
<section class="lista-de-cards">
    {% for hamburguer in hamburguer_list %}
    <article class="card">
        <a href="{% url 'hamburguer:detail' hamburguer.id %}"><img src="{{ hamburguer.poster_url }}" height='300'
            alt="Poster da Hamburgueria {{ hamburguer.name}}"></a>
        <p>{{ hamburguer.name }} </p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma Hamburgueria.</p>
{% endif %}

{% endblock content %}

hamburguer/templates/hamburguer/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Listas de Hamburguerias</h2>

<section>
    {% for list in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'hamburguer:category_detail' list.id %}"><h3>{{list.name}} (de {{ list.author }}) </h3></a>
            
        </header>
        <div class="lista-de-cards">
            {% for hamburguer in list.hamburguer.all %}
            <div class="card">
                <a href="{% url 'hamburguer:detail' hamburguer.id %}"><img src="{{ hamburguer.poster_url }}"
                        alt="Poster da Hamburgueria {{ hamburguer.name}}"></a>
                <p>{{ hamburguer.name }} ({{ hamburguer.release_year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'hamburguer:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

hamburguer/templates/hamburguer/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar sobre uma Hamburgueria {{ hamburguer.name }} ({{ hamburguer.release_year }})</h2>

<form action="{% url 'hamburguer:review' hamburguer.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'hamburguer:detail' hamburguer.id %}">Voltar para a página da Hamburgueria</a></p>
{% endblock content %}

hamburguer/templates/hamburguer/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca Hamburguerias por Nome</h2>
<form action="{% url 'hamburguer:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if hamburguer_list %}
<section class="lista-de-cards">
    {% for hamburguer in hamburguer_list %}
    <article class="card">
        <img src="{{ hamburguer.poster_url }}" alt="Poster da Hamburgueria {{ hamburguer.name}}" height=300>
        <p>{{ hamburguer.name }} </p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma Hamburgueria para a busca.</p>
{% endif %}

{% endblock content %}

hamburguer/templates/hamburguer/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados da Hamburgueria {{ hamburguer.name }}</h2>
<form method="POST" action="{% url 'hamburguer:update' hamburguer.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}